[2025-01-01T23:45:22.824+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-01T23:45:22.840+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prediction_dag_v1.evaluate_status manual__2025-01-01T23:44:50.388107+00:00 [queued]>
[2025-01-01T23:45:22.848+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prediction_dag_v1.evaluate_status manual__2025-01-01T23:44:50.388107+00:00 [queued]>
[2025-01-01T23:45:22.849+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-01T23:45:22.864+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): evaluate_status> on 2025-01-01 23:44:50.388107+00:00
[2025-01-01T23:45:22.874+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=996) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-01T23:45:22.877+0000] {standard_task_runner.py:72} INFO - Started process 998 to run task
[2025-01-01T23:45:22.876+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'prediction_dag_v1', 'evaluate_status', 'manual__2025-01-01T23:44:50.388107+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/02_prediction/02_prediction_v1.py', '--cfg-path', '/tmp/tmpi38vgiit']
[2025-01-01T23:45:22.878+0000] {standard_task_runner.py:105} INFO - Job 37: Subtask evaluate_status
[2025-01-01T23:45:22.937+0000] {task_command.py:467} INFO - Running <TaskInstance: prediction_dag_v1.evaluate_status manual__2025-01-01T23:44:50.388107+00:00 [running]> on host 24eea4b1b7f8
[2025-01-01T23:45:23.031+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='cm' AIRFLOW_CTX_DAG_ID='prediction_dag_v1' AIRFLOW_CTX_TASK_ID='evaluate_status' AIRFLOW_CTX_EXECUTION_DATE='2025-01-01T23:44:50.388107+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-01T23:44:50.388107+00:00'
[2025-01-01T23:45:23.033+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-01T23:45:23.033+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-01T23:45:23.034+0000] {logging_mixin.py:190} INFO - Current task name:evaluate_status state:running start_date:2025-01-01 23:45:22.841191+00:00
[2025-01-01T23:45:23.035+0000] {logging_mixin.py:190} INFO - Dag name:prediction_dag_v1 and current dag run status:running
[2025-01-01T23:45:23.035+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-01T23:45:23.043+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-01-01T23:45:23.047+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/02_prediction/02_prediction_v1.py", line 28, in evaluate_status
    raise AirflowFailException("error")
airflow.exceptions.AirflowFailException: error
[2025-01-01T23:45:23.067+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-01T23:45:23.068+0000] {logging_mixin.py:190} INFO - Task start:2025-01-01 23:45:22.841191+00:00 end:2025-01-01 23:45:23.066753+00:00 duration:0.225562
[2025-01-01T23:45:23.068+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): evaluate_status> dag:<DAG: prediction_dag_v1> dagrun:<DagRun prediction_dag_v1 @ 2025-01-01 23:44:50.388107+00:00: manual__2025-01-01T23:44:50.388107+00:00, state:running, queued_at: 2025-01-01 23:44:50.397173+00:00. externally triggered: True>
[2025-01-01T23:45:23.069+0000] {logging_mixin.py:190} INFO - Failure caused by error
[2025-01-01T23:45:23.069+0000] {taskinstance.py:1225} INFO - Immediate failure requested. Marking task as FAILED. dag_id=prediction_dag_v1, task_id=evaluate_status, run_id=manual__2025-01-01T23:44:50.388107+00:00, execution_date=20250101T234450, start_date=20250101T234522, end_date=20250101T234523
[2025-01-01T23:45:23.081+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-01T23:45:23.082+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 37 for task evaluate_status (error; 998)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/02_prediction/02_prediction_v1.py", line 28, in evaluate_status
    raise AirflowFailException("error")
airflow.exceptions.AirflowFailException: error
[2025-01-01T23:45:23.132+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-01T23:45:23.147+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-01T23:45:23.149+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
