[2025-01-01T21:05:08.982+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-01T21:05:09.006+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prediction_dag_v1.predict_model manual__2025-01-01T21:05:00.647881+00:00 [queued]>
[2025-01-01T21:05:09.014+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prediction_dag_v1.predict_model manual__2025-01-01T21:05:00.647881+00:00 [queued]>
[2025-01-01T21:05:09.016+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-01T21:05:09.030+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): predict_model> on 2025-01-01 21:05:00.647881+00:00
[2025-01-01T21:05:09.039+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=156) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-01T21:05:09.042+0000] {standard_task_runner.py:72} INFO - Started process 158 to run task
[2025-01-01T21:05:09.043+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'prediction_dag_v1', 'predict_model', 'manual__2025-01-01T21:05:00.647881+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/02_prediction/02_prediction_v1.py', '--cfg-path', '/tmp/tmpyople17s']
[2025-01-01T21:05:09.045+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask predict_model
[2025-01-01T21:05:09.125+0000] {task_command.py:467} INFO - Running <TaskInstance: prediction_dag_v1.predict_model manual__2025-01-01T21:05:00.647881+00:00 [running]> on host 935cb972f608
[2025-01-01T21:05:09.624+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='cm' AIRFLOW_CTX_DAG_ID='prediction_dag_v1' AIRFLOW_CTX_TASK_ID='predict_model' AIRFLOW_CTX_EXECUTION_DATE='2025-01-01T21:05:00.647881+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-01T21:05:00.647881+00:00'
[2025-01-01T21:05:09.625+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-01T21:05:09.625+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-01T21:05:09.626+0000] {logging_mixin.py:190} INFO - Current task name:predict_model state:running start_date:2025-01-01 21:05:09.007388+00:00
[2025-01-01T21:05:09.627+0000] {logging_mixin.py:190} INFO - Dag name:prediction_dag_v1 and current dag run status:running
[2025-01-01T21:05:09.628+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-01T21:05:09.629+0000] {process_utils.py:186} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venv6mg4okcg --system-site-packages --python=python
[2025-01-01T21:05:09.631+0000] {process_utils.py:190} INFO - Output:
[2025-01-01T21:05:10.976+0000] {process_utils.py:194} INFO - created virtual environment CPython3.12.7.final.0-64 in 680ms
[2025-01-01T21:05:10.978+0000] {process_utils.py:194} INFO -   creator CPython3Posix(dest=/tmp/venv6mg4okcg, clear=False, no_vcs_ignore=False, global=True)
[2025-01-01T21:05:10.979+0000] {process_utils.py:194} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2025-01-01T21:05:10.980+0000] {process_utils.py:194} INFO -     added seed packages: pip==24.3.1
[2025-01-01T21:05:10.981+0000] {process_utils.py:194} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-01-01T21:05:11.023+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venv6mg4okcg/bin/pip install -r /tmp/venv6mg4okcg/requirements.txt
[2025-01-01T21:05:11.025+0000] {process_utils.py:190} INFO - Output:
[2025-01-01T21:05:12.932+0000] {process_utils.py:194} INFO - Collecting feature-engine==1.8.2 (from -r /tmp/venv6mg4okcg/requirements.txt (line 1))
[2025-01-01T21:05:13.034+0000] {process_utils.py:194} INFO -   Downloading feature_engine-1.8.2-py2.py3-none-any.whl.metadata (9.9 kB)
[2025-01-01T21:05:13.090+0000] {process_utils.py:194} INFO - Collecting joblib==1.3.2 (from -r /tmp/venv6mg4okcg/requirements.txt (line 2))
[2025-01-01T21:05:13.098+0000] {process_utils.py:194} INFO -   Downloading joblib-1.3.2-py3-none-any.whl.metadata (5.4 kB)
[2025-01-01T21:05:13.109+0000] {process_utils.py:194} INFO - Requirement already satisfied: numpy==1.26.4 in /home/***/.local/lib/python3.12/site-packages (from -r /tmp/venv6mg4okcg/requirements.txt (line 3)) (1.26.4)
[2025-01-01T21:05:13.280+0000] {process_utils.py:194} INFO - Collecting pandas==2.2.3 (from -r /tmp/venv6mg4okcg/requirements.txt (line 4))
[2025-01-01T21:05:13.288+0000] {process_utils.py:194} INFO -   Downloading pandas-2.2.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (89 kB)
[2025-01-01T21:05:13.353+0000] {process_utils.py:194} INFO - Requirement already satisfied: pendulum in /home/***/.local/lib/python3.12/site-packages (from -r /tmp/venv6mg4okcg/requirements.txt (line 5)) (3.0.0)
[2025-01-01T21:05:13.506+0000] {process_utils.py:194} INFO - Collecting scikit-learn==1.5.2 (from -r /tmp/venv6mg4okcg/requirements.txt (line 6))
[2025-01-01T21:05:13.518+0000] {process_utils.py:194} INFO -   Downloading scikit_learn-1.5.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
[2025-01-01T21:05:13.774+0000] {process_utils.py:194} INFO - Collecting scipy>=1.4.1 (from feature-engine==1.8.2->-r /tmp/venv6mg4okcg/requirements.txt (line 1))
[2025-01-01T21:05:13.782+0000] {process_utils.py:194} INFO -   Downloading scipy-1.14.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
[2025-01-01T21:05:14.041+0000] {process_utils.py:194} INFO - Collecting statsmodels>=0.11.1 (from feature-engine==1.8.2->-r /tmp/venv6mg4okcg/requirements.txt (line 1))
[2025-01-01T21:05:14.051+0000] {process_utils.py:194} INFO -   Downloading statsmodels-0.14.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.2 kB)
[2025-01-01T21:05:14.074+0000] {process_utils.py:194} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.2.3->-r /tmp/venv6mg4okcg/requirements.txt (line 4)) (2.9.0.post0)
[2025-01-01T21:05:14.075+0000] {process_utils.py:194} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.2.3->-r /tmp/venv6mg4okcg/requirements.txt (line 4)) (2024.2)
[2025-01-01T21:05:14.076+0000] {process_utils.py:194} INFO - Requirement already satisfied: tzdata>=2022.7 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.2.3->-r /tmp/venv6mg4okcg/requirements.txt (line 4)) (2024.2)
[2025-01-01T21:05:14.126+0000] {process_utils.py:194} INFO - Collecting threadpoolctl>=3.1.0 (from scikit-learn==1.5.2->-r /tmp/venv6mg4okcg/requirements.txt (line 6))
[2025-01-01T21:05:14.143+0000] {process_utils.py:194} INFO -   Downloading threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
[2025-01-01T21:05:14.159+0000] {process_utils.py:194} INFO - Requirement already satisfied: time-machine>=2.6.0 in /home/***/.local/lib/python3.12/site-packages (from pendulum->-r /tmp/venv6mg4okcg/requirements.txt (line 5)) (2.16.0)
[2025-01-01T21:05:14.161+0000] {process_utils.py:194} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas==2.2.3->-r /tmp/venv6mg4okcg/requirements.txt (line 4)) (1.16.0)
[2025-01-01T21:05:14.303+0000] {process_utils.py:194} INFO - Collecting patsy>=0.5.6 (from statsmodels>=0.11.1->feature-engine==1.8.2->-r /tmp/venv6mg4okcg/requirements.txt (line 1))
[2025-01-01T21:05:14.314+0000] {process_utils.py:194} INFO -   Downloading patsy-1.0.1-py2.py3-none-any.whl.metadata (3.3 kB)
[2025-01-01T21:05:14.326+0000] {process_utils.py:194} INFO - Requirement already satisfied: packaging>=21.3 in /home/***/.local/lib/python3.12/site-packages (from statsmodels>=0.11.1->feature-engine==1.8.2->-r /tmp/venv6mg4okcg/requirements.txt (line 1)) (24.1)
[2025-01-01T21:05:14.346+0000] {process_utils.py:194} INFO - Downloading feature_engine-1.8.2-py2.py3-none-any.whl (374 kB)
[2025-01-01T21:05:14.446+0000] {process_utils.py:194} INFO - Downloading joblib-1.3.2-py3-none-any.whl (302 kB)
[2025-01-01T21:05:14.531+0000] {process_utils.py:194} INFO - Downloading pandas-2.2.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.7 MB)
[2025-01-01T21:05:17.385+0000] {process_utils.py:194} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.7/12.7 MB 4.5 MB/s eta 0:00:00
[2025-01-01T21:05:17.396+0000] {process_utils.py:194} INFO - Downloading scikit_learn-1.5.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.9 MB)
[2025-01-01T21:05:20.567+0000] {process_utils.py:194} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.9/12.9 MB 4.1 MB/s eta 0:00:00
[2025-01-01T21:05:20.577+0000] {process_utils.py:194} INFO - Downloading scipy-1.14.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (40.8 MB)
[2025-01-01T21:05:30.477+0000] {process_utils.py:194} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.8/40.8 MB 4.1 MB/s eta 0:00:00
[2025-01-01T21:05:30.487+0000] {process_utils.py:194} INFO - Downloading statsmodels-0.14.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (10.7 MB)
[2025-01-01T21:05:32.303+0000] {process_utils.py:194} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 5.9 MB/s eta 0:00:00
[2025-01-01T21:05:32.316+0000] {process_utils.py:194} INFO - Downloading threadpoolctl-3.5.0-py3-none-any.whl (18 kB)
[2025-01-01T21:05:32.349+0000] {process_utils.py:194} INFO - Downloading patsy-1.0.1-py2.py3-none-any.whl (232 kB)
[2025-01-01T21:05:33.133+0000] {process_utils.py:194} INFO - Installing collected packages: threadpoolctl, scipy, patsy, joblib, scikit-learn, pandas, statsmodels, feature-engine
[2025-01-01T21:05:40.917+0000] {process_utils.py:194} INFO -   Attempting uninstall: pandas
[2025-01-01T21:05:40.923+0000] {process_utils.py:194} INFO -     Found existing installation: pandas 2.1.4
[2025-01-01T21:05:40.925+0000] {process_utils.py:194} INFO -     Not uninstalling pandas at /home/***/.local/lib/python3.12/site-packages, outside environment /tmp/venv6mg4okcg
[2025-01-01T21:05:40.927+0000] {process_utils.py:194} INFO -     Can't uninstall 'pandas'. No files were found to uninstall.
[2025-01-01T21:05:50.456+0000] {process_utils.py:194} INFO - ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
[2025-01-01T21:05:50.457+0000] {process_utils.py:194} INFO - apache-***-providers-google 10.25.0 requires pandas<2.2,>=2.1.2; python_version >= "3.9", but you have pandas 2.2.3 which is incompatible.
[2025-01-01T21:05:50.458+0000] {process_utils.py:194} INFO - apache-***-providers-snowflake 5.8.0 requires pandas<2.2,>=2.1.2; python_version >= "3.9", but you have pandas 2.2.3 which is incompatible.
[2025-01-01T21:05:50.459+0000] {process_utils.py:194} INFO - Successfully installed feature-engine-1.8.2 joblib-1.3.2 pandas-2.2.3 patsy-1.0.1 scikit-learn-1.5.2 scipy-1.14.1 statsmodels-0.14.4 threadpoolctl-3.5.0
[2025-01-01T21:05:50.977+0000] {python.py:513} INFO - Use 'pickle' as serializer.
[2025-01-01T21:05:51.325+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 505, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 870, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 544, in _execute_python_callable_in_subprocess
    self._write_args(input_path)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 514, in _write_args
    file.write_bytes(self.pickling_library.dumps({"args": self.op_args, "kwargs": self.op_kwargs}))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_pickle.PicklingError: Can't pickle <function task_extract_execution_date at 0x7fd61e7a3ba0>: it's not the same object as common.prediction_task.task_extract_execution_date
[2025-01-01T21:05:51.362+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-01T21:05:51.364+0000] {logging_mixin.py:190} INFO - Task start:2025-01-01 21:05:09.007388+00:00 end:2025-01-01 21:05:51.361117+00:00 duration:42.353729
[2025-01-01T21:05:51.365+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonVirtualenvDecoratedOperator): predict_model> dag:<DAG: prediction_dag_v1> dagrun:<DagRun prediction_dag_v1 @ 2025-01-01 21:05:00.647881+00:00: manual__2025-01-01T21:05:00.647881+00:00, state:running, queued_at: 2025-01-01 21:05:00.673935+00:00. externally triggered: True>
[2025-01-01T21:05:51.367+0000] {logging_mixin.py:190} INFO - Failure caused by Can't pickle <function task_extract_execution_date at 0x7fd61e7a3ba0>: it's not the same object as common.prediction_task.task_extract_execution_date
[2025-01-01T21:05:51.368+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=prediction_dag_v1, task_id=predict_model, run_id=manual__2025-01-01T21:05:00.647881+00:00, execution_date=20250101T210500, start_date=20250101T210509, end_date=20250101T210551
[2025-01-01T21:05:51.400+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-01T21:05:51.402+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 4 for task predict_model (Can't pickle <function task_extract_execution_date at 0x7fd61e7a3ba0>: it's not the same object as common.prediction_task.task_extract_execution_date; 158)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 505, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 870, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 544, in _execute_python_callable_in_subprocess
    self._write_args(input_path)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 514, in _write_args
    file.write_bytes(self.pickling_library.dumps({"args": self.op_args, "kwargs": self.op_kwargs}))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_pickle.PicklingError: Can't pickle <function task_extract_execution_date at 0x7fd61e7a3ba0>: it's not the same object as common.prediction_task.task_extract_execution_date
[2025-01-01T21:05:51.452+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-01T21:05:51.499+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-01T21:05:51.505+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
