[2024-12-28T21:07:41.662+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-28T21:07:41.689+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prediction_dag_v1.task_executiondate manual__2024-12-28T21:07:32.187718+00:00 [queued]>
[2024-12-28T21:07:41.701+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prediction_dag_v1.task_executiondate manual__2024-12-28T21:07:32.187718+00:00 [queued]>
[2024-12-28T21:07:41.702+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-28T21:07:41.725+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): task_executiondate> on 2024-12-28 21:07:32.187718+00:00
[2024-12-28T21:07:41.740+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=113) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-28T21:07:41.746+0000] {standard_task_runner.py:72} INFO - Started process 115 to run task
[2024-12-28T21:07:41.748+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'prediction_dag_v1', 'task_executiondate', 'manual__2024-12-28T21:07:32.187718+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/02_prediction/02_prediction_v1.py', '--cfg-path', '/tmp/tmp3n48s0nq']
[2024-12-28T21:07:41.751+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask task_executiondate
[2024-12-28T21:07:41.901+0000] {task_command.py:467} INFO - Running <TaskInstance: prediction_dag_v1.task_executiondate manual__2024-12-28T21:07:32.187718+00:00 [running]> on host cdcf898286b8
[2024-12-28T21:07:42.591+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='cm' AIRFLOW_CTX_DAG_ID='prediction_dag_v1' AIRFLOW_CTX_TASK_ID='task_executiondate' AIRFLOW_CTX_EXECUTION_DATE='2024-12-28T21:07:32.187718+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-28T21:07:32.187718+00:00'
[2024-12-28T21:07:42.594+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-28T21:07:42.595+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-28T21:07:42.596+0000] {logging_mixin.py:190} INFO - Current task name:task_executiondate state:running start_date:2024-12-28 21:07:41.691093+00:00
[2024-12-28T21:07:42.598+0000] {logging_mixin.py:190} INFO - Dag name:prediction_dag_v1 and current dag run status:running
[2024-12-28T21:07:42.598+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-28T21:07:42.603+0000] {logging_mixin.py:190} INFO - 2024-12-28
[2024-12-28T21:07:42.616+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-12-28T21:07:42.623+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/common/prediction_task.py", line 124, in task_executiondate
    err = 1/0
          ~^~
ZeroDivisionError: division by zero
[2024-12-28T21:07:42.651+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-28T21:07:42.652+0000] {logging_mixin.py:190} INFO - Task start:2024-12-28 21:07:41.691093+00:00 end:2024-12-28 21:07:42.651432+00:00 duration:0.960339
[2024-12-28T21:07:42.653+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): task_executiondate> dag:<DAG: prediction_dag_v1> dagrun:<DagRun prediction_dag_v1 @ 2024-12-28 21:07:32.187718+00:00: manual__2024-12-28T21:07:32.187718+00:00, state:running, queued_at: 2024-12-28 21:07:32.217980+00:00. externally triggered: True>
[2024-12-28T21:07:42.654+0000] {logging_mixin.py:190} INFO - Failure caused by division by zero
[2024-12-28T21:07:42.655+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=prediction_dag_v1, task_id=task_executiondate, run_id=manual__2024-12-28T21:07:32.187718+00:00, execution_date=20241228T210732, start_date=20241228T210741, end_date=20241228T210742
[2024-12-28T21:07:42.674+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-28T21:07:42.676+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 4 for task task_executiondate (division by zero; 115)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/common/prediction_task.py", line 124, in task_executiondate
    err = 1/0
          ~^~
ZeroDivisionError: division by zero
[2024-12-28T21:07:42.731+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-28T21:07:42.782+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-28T21:07:42.787+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
