[2025-01-01T17:40:57.024+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-01T17:40:57.049+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prediction_dag_v1.predict_model manual__2025-01-01T17:40:37.509939+00:00 [queued]>
[2025-01-01T17:40:57.063+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prediction_dag_v1.predict_model manual__2025-01-01T17:40:37.509939+00:00 [queued]>
[2025-01-01T17:40:57.065+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-01-01T17:40:57.080+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): predict_model> on 2025-01-01 17:40:37.509939+00:00
[2025-01-01T17:40:57.086+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=717) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-01T17:40:57.089+0000] {standard_task_runner.py:72} INFO - Started process 719 to run task
[2025-01-01T17:40:57.088+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'prediction_dag_v1', 'predict_model', 'manual__2025-01-01T17:40:37.509939+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/02_prediction/02_prediction_v1.py', '--cfg-path', '/tmp/tmpcl99pk29']
[2025-01-01T17:40:57.091+0000] {standard_task_runner.py:105} INFO - Job 11: Subtask predict_model
[2025-01-01T17:40:57.148+0000] {task_command.py:467} INFO - Running <TaskInstance: prediction_dag_v1.predict_model manual__2025-01-01T17:40:37.509939+00:00 [running]> on host cbeec914397d
[2025-01-01T17:40:57.618+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='cm' AIRFLOW_CTX_DAG_ID='prediction_dag_v1' AIRFLOW_CTX_TASK_ID='predict_model' AIRFLOW_CTX_EXECUTION_DATE='2025-01-01T17:40:37.509939+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-01T17:40:37.509939+00:00'
[2025-01-01T17:40:57.620+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-01T17:40:57.622+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-01T17:40:57.623+0000] {logging_mixin.py:190} INFO - Current task name:predict_model state:running start_date:2025-01-01 17:40:57.050957+00:00
[2025-01-01T17:40:57.625+0000] {logging_mixin.py:190} INFO - Dag name:prediction_dag_v1 and current dag run status:running
[2025-01-01T17:40:57.627+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-01T17:40:57.630+0000] {process_utils.py:186} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venvnt47f6_5 --python=python
[2025-01-01T17:40:57.633+0000] {process_utils.py:190} INFO - Output:
[2025-01-01T17:40:58.556+0000] {process_utils.py:194} INFO - created virtual environment CPython3.12.7.final.0-64 in 266ms
[2025-01-01T17:40:58.558+0000] {process_utils.py:194} INFO -   creator CPython3Posix(dest=/tmp/venvnt47f6_5, clear=False, no_vcs_ignore=False, global=False)
[2025-01-01T17:40:58.559+0000] {process_utils.py:194} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2025-01-01T17:40:58.559+0000] {process_utils.py:194} INFO -     added seed packages: pip==24.3.1
[2025-01-01T17:40:58.560+0000] {process_utils.py:194} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-01-01T17:40:58.583+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venvnt47f6_5/bin/pip install -r /tmp/venvnt47f6_5/requirements.txt
[2025-01-01T17:40:58.584+0000] {process_utils.py:190} INFO - Output:
[2025-01-01T17:41:00.194+0000] {process_utils.py:194} INFO - Collecting *** (from -r /tmp/venvnt47f6_5/requirements.txt (line 1))
[2025-01-01T17:41:00.213+0000] {process_utils.py:194} INFO -   Using cached ***-0.6.tar.gz (1.2 kB)
[2025-01-01T17:41:00.214+0000] {process_utils.py:194} INFO -   Installing build dependencies: started
[2025-01-01T17:41:02.331+0000] {process_utils.py:194} INFO -   Installing build dependencies: finished with status 'done'
[2025-01-01T17:41:02.332+0000] {process_utils.py:194} INFO -   Getting requirements to build wheel: started
[2025-01-01T17:41:02.928+0000] {process_utils.py:194} INFO -   Getting requirements to build wheel: finished with status 'error'
[2025-01-01T17:41:02.936+0000] {process_utils.py:194} INFO -   error: subprocess-exited-with-error
[2025-01-01T17:41:02.937+0000] {process_utils.py:194} INFO - 
[2025-01-01T17:41:02.938+0000] {process_utils.py:194} INFO -   × Getting requirements to build wheel did not run successfully.
[2025-01-01T17:41:02.939+0000] {process_utils.py:194} INFO -   │ exit code: 1
[2025-01-01T17:41:02.940+0000] {process_utils.py:194} INFO -   ╰─> [26 lines of output]
[2025-01-01T17:41:02.941+0000] {process_utils.py:194} INFO -       running egg_info
[2025-01-01T17:41:02.942+0000] {process_utils.py:194} INFO -       writing ***.egg-info/PKG-INFO
[2025-01-01T17:41:02.943+0000] {process_utils.py:194} INFO -       writing dependency_links to ***.egg-info/dependency_links.txt
[2025-01-01T17:41:02.944+0000] {process_utils.py:194} INFO -       writing top-level names to ***.egg-info/top_level.txt
[2025-01-01T17:41:02.945+0000] {process_utils.py:194} INFO -       reading manifest file '***.egg-info/SOURCES.txt'
[2025-01-01T17:41:02.946+0000] {process_utils.py:194} INFO -       writing manifest file '***.egg-info/SOURCES.txt'
[2025-01-01T17:41:02.947+0000] {process_utils.py:194} INFO -       Traceback (most recent call last):
[2025-01-01T17:41:02.948+0000] {process_utils.py:194} INFO -         File "/tmp/venvnt47f6_5/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
[2025-01-01T17:41:02.949+0000] {process_utils.py:194} INFO -           main()
[2025-01-01T17:41:02.950+0000] {process_utils.py:194} INFO -         File "/tmp/venvnt47f6_5/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
[2025-01-01T17:41:02.950+0000] {process_utils.py:194} INFO -           json_out['return_val'] = hook(**hook_input['kwargs'])
[2025-01-01T17:41:02.951+0000] {process_utils.py:194} INFO -                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-01-01T17:41:02.952+0000] {process_utils.py:194} INFO -         File "/tmp/venvnt47f6_5/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
[2025-01-01T17:41:02.952+0000] {process_utils.py:194} INFO -           return hook(config_settings)
[2025-01-01T17:41:02.953+0000] {process_utils.py:194} INFO -                  ^^^^^^^^^^^^^^^^^^^^^
[2025-01-01T17:41:02.954+0000] {process_utils.py:194} INFO -         File "/tmp/pip-build-env-y4prmk_q/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
[2025-01-01T17:41:02.954+0000] {process_utils.py:194} INFO -           return self._get_build_requires(config_settings, requirements=[])
[2025-01-01T17:41:02.955+0000] {process_utils.py:194} INFO -                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-01-01T17:41:02.956+0000] {process_utils.py:194} INFO -         File "/tmp/pip-build-env-y4prmk_q/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
[2025-01-01T17:41:02.956+0000] {process_utils.py:194} INFO -           self.run_setup()
[2025-01-01T17:41:02.957+0000] {process_utils.py:194} INFO -         File "/tmp/pip-build-env-y4prmk_q/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 522, in run_setup
[2025-01-01T17:41:02.958+0000] {process_utils.py:194} INFO -           super().run_setup(setup_script=setup_script)
[2025-01-01T17:41:02.959+0000] {process_utils.py:194} INFO -         File "/tmp/pip-build-env-y4prmk_q/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 320, in run_setup
[2025-01-01T17:41:02.959+0000] {process_utils.py:194} INFO -           exec(code, locals())
[2025-01-01T17:41:02.960+0000] {process_utils.py:194} INFO -         File "<string>", line 32, in <module>
[2025-01-01T17:41:02.961+0000] {process_utils.py:194} INFO -       RuntimeError: Please install package apache-*** instead of ***
[2025-01-01T17:41:02.961+0000] {process_utils.py:194} INFO -       [end of output]
[2025-01-01T17:41:02.962+0000] {process_utils.py:194} INFO - 
[2025-01-01T17:41:02.963+0000] {process_utils.py:194} INFO -   note: This error originates from a subprocess, and is likely not a problem with pip.
[2025-01-01T17:41:03.099+0000] {process_utils.py:194} INFO - error: subprocess-exited-with-error
[2025-01-01T17:41:03.114+0000] {process_utils.py:194} INFO - 
[2025-01-01T17:41:03.115+0000] {process_utils.py:194} INFO - × Getting requirements to build wheel did not run successfully.
[2025-01-01T17:41:03.116+0000] {process_utils.py:194} INFO - │ exit code: 1
[2025-01-01T17:41:03.116+0000] {process_utils.py:194} INFO - ╰─> See above for output.
[2025-01-01T17:41:03.117+0000] {process_utils.py:194} INFO - 
[2025-01-01T17:41:03.118+0000] {process_utils.py:194} INFO - note: This error originates from a subprocess, and is likely not a problem with pip.
[2025-01-01T17:41:03.211+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 505, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 868, in execute_callable
    self._prepare_venv(tmp_path)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 769, in _prepare_venv
    prepare_virtualenv(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/python_virtualenv.py", line 119, in prepare_virtualenv
    execute_in_subprocess(pip_cmd)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/process_utils.py", line 175, in execute_in_subprocess
    execute_in_subprocess_with_kwargs(cmd, cwd=cwd, env=env)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/process_utils.py", line 198, in execute_in_subprocess_with_kwargs
    raise subprocess.CalledProcessError(exit_code, cmd)
subprocess.CalledProcessError: Command '['/tmp/venvnt47f6_5/bin/pip', 'install', '-r', '/tmp/venvnt47f6_5/requirements.txt']' returned non-zero exit status 1.
[2025-01-01T17:41:03.229+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-01T17:41:03.240+0000] {logging_mixin.py:190} INFO - Task start:2025-01-01 17:40:57.050957+00:00 end:2025-01-01 17:41:03.229161+00:00 duration:6.178204
[2025-01-01T17:41:03.243+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonVirtualenvDecoratedOperator): predict_model> dag:<DAG: prediction_dag_v1> dagrun:<DagRun prediction_dag_v1 @ 2025-01-01 17:40:37.509939+00:00: manual__2025-01-01T17:40:37.509939+00:00, state:running, queued_at: 2025-01-01 17:40:37.533618+00:00. externally triggered: True>
[2025-01-01T17:41:03.263+0000] {logging_mixin.py:190} INFO - Failure caused by Command '['/tmp/venvnt47f6_5/bin/pip', 'install', '-r', '/tmp/venvnt47f6_5/requirements.txt']' returned non-zero exit status 1.
[2025-01-01T17:41:03.271+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=prediction_dag_v1, task_id=predict_model, run_id=manual__2025-01-01T17:40:37.509939+00:00, execution_date=20250101T174037, start_date=20250101T174057, end_date=20250101T174103
[2025-01-01T17:41:03.292+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-01T17:41:03.295+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 11 for task predict_model (Command '['/tmp/venvnt47f6_5/bin/pip', 'install', '-r', '/tmp/venvnt47f6_5/requirements.txt']' returned non-zero exit status 1.; 719)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 505, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 868, in execute_callable
    self._prepare_venv(tmp_path)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 769, in _prepare_venv
    prepare_virtualenv(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/python_virtualenv.py", line 119, in prepare_virtualenv
    execute_in_subprocess(pip_cmd)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/process_utils.py", line 175, in execute_in_subprocess
    execute_in_subprocess_with_kwargs(cmd, cwd=cwd, env=env)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/process_utils.py", line 198, in execute_in_subprocess_with_kwargs
    raise subprocess.CalledProcessError(exit_code, cmd)
subprocess.CalledProcessError: Command '['/tmp/venvnt47f6_5/bin/pip', 'install', '-r', '/tmp/venvnt47f6_5/requirements.txt']' returned non-zero exit status 1.
[2025-01-01T17:41:03.327+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-01T17:41:03.362+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-01T17:41:03.375+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
